const MAIN_CONTENT ="MAIN_CONTENT";
const INTRO_SLIDES = "INTRO_SLIDE";
const AUTHENTICATION = "AUTHENTICATION";
const LOG_IN  = "LOGIN";
const SIGN_UP = "SIGNUP";
const FORGET_PASSWORD = "FORGET_PASSWORD";
const ROOT_SCENE = "ROOT_SCENE";
const REGISTRATION_ONE = 'REGISTRATION_ONE';
const REGISTRATION_TWO = "REGISTRATION_TWO";
const REGISTRATION_THREE = 'REGISTRATION_THREE';

const DASH_BOARD = "DASHBOARD";
const CHAT_SCREEN = "CHATSCREEN";
const EXPLORE_SCREEN = "EXPLORESCREEN";
const PROFILE_SCREEN = "PROFILESCREEN";
const OPEN_SCREEN = "OPENSCREEN";

// suffixes
const WRAPPER_KEY_SUFFIX = 'Wrapper';
const NAVIGATOR_KEY_SUFFIX = 'Navigator';
const TABS_KEY_SUFFIX = 'Tabs';
const CONTENT_KEY_SUFFIX = 'Content';

export default {

    MAIN_CONTENT,
    AUTHENTICATION,
    LOG_IN,
    ROOT_SCENE,
    SIGN_UP,
    FORGET_PASSWORD,
    INTRO_SLIDES,
    WRAPPER_KEY_SUFFIX,
    NAVIGATOR_KEY_SUFFIX,
    TABS_KEY_SUFFIX,
    CONTENT_KEY_SUFFIX,
    REGISTRATION_ONE,
    REGISTRATION_TWO,
    REGISTRATION_THREE,

    DASH_BOARD,
    CHAT_SCREEN,
    EXPLORE_SCREEN,
    PROFILE_SCREEN,
    OPEN_SCREEN,
};
